name: test-trigger

on:
  push:
    branches:
      - develop
      - release
      - main
      - master

jobs:
    test-subtree:
        name: test
        runs-on: ubuntu-latest
        steps:
            - name: Trigger on management repository
              uses: peter-evans/repository-dispatch@v2
              with:
                token: ${{ secrets.ACTION_TOKEN }}
                repository: reconlabs-luke/management
                event-type: metarecon3
                client-payload: '{"branch": "${{ github.ref_name }}", "sha": "${{ github.sha }}"}'