name: plicar cicd

on:
  push:
    branches: 
      - "master"
      - "release"
      - "develop"
      - "main"

jobs:
  push-to-subtree:
    name: Push to subtree repository
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Push to subtree
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:reconlabs-luke/sdfstudio.git
          BRANCH: ${GITHUB_REF_NAME}
          FOLDER: sdfstudio
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}

