name: test-subtree

on:
  pull_request:
    types:
      - closed
    branches: 
      - "release"
      - "develop"
      - "feature/*"
  push:
    branches:
      - "master"
      - "main"
      - "release"
      - "develop"
      - "feature/*"

jobs:
  push-to-subtree:
    name: Push to subtree repository
    runs-on: ubuntu-latest
    env:
      TARGET_GROUP: reconlabs-luke
      TARGET_REPOSITORY: sdfstudio
      TARGET_BRANCH: ${{ github.ref_name }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Add ssh private key
        run: |
          mkdir -p ~/.ssh && echo "${{ secrets.DEPLOY_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.DEPLOY_PUB_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 400 ~/.ssh/id_rsa
      - name: Add to ssh agent
        run: |
          eval $(ssh-agent)
          ssh-add ~/.ssh/id_rsa
          ssh-add -l
      - name: Add subtree's remote repository 
        run: |
          git remote add ${TARGET_REPOSITORY} git@github.com:reconlabs-luke/sdfstudio.git
          git remote update
      - if: github.event.pull_request.merged == true
        name: If Merged, target branch will be set base branch
        run: |
          export TARGET_BRANCH=${{ github.base_ref }}
      - if: always()
        name: Pull from subtree repository
        run: |
          git config pull.rebase true
          git pull --squash -s subtree ${TARGET_REPOSITORY} ${TARGET_BRANCH}
      # - if: always()
      #   name: Push to subtree repository
      #   run: |
      #       git push ${TARGET_REPOSITORY} `git subtree split --prefix ${TARGET_REPOSITORY} ${TARGET_BRANCH}`:${TARGET_BRANCH} --force