name: test

on:
  push:
    branches:
      - "feature/*"
    
jobs:
    test-subtree:
        name: test
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v2
            - name: Make private key
              run: |
                mkdir -p ${HOME}/.ssh
                echo "${{ secrets.DEPLOY_PRIVATE_KEY }}" > ${HOME}/.ssh/id_rsa
                echo "${{ secrets.DEPLOY_PUB_KEY }}" > ${HOME}/.ssh/id_rsa.pub
            - name: Pull test
              run: |
                git config --global user.name reconlabs-luke
                git config --global user.email luke@reconlabs.ai
                sudo git remote add sub reconlabs-luke@github.com:reconlabs-luke/sdfstudio.git
                sudo git subtree pull --prefix=sdfstudio sub develop