name: test

on:
  push:
    branches:
      - "feature/*"
    
jobs:
    test-subtree:
        name: test
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v3
            - name: Set On the Branch
              run: |
                git config -f .gitmodules submodule.submodule.branch ${{ github.base_ref }}
                git submodule update --remote --recursive
                